---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx 
  namespace: my-namespace
spec: 
  replicas: 3

  selector: 
    matchLabels: 
       app: nginx 

  template: 
    metadata: 
      labels: 
        app: nginx

    spec: 
      containers:
      - name: nginx-container 
        image: nginx:latest 
        volumeMounts: 
        - name: my-volume
          mountPath:  /usr/share/nginx/html 
      volumes: 
      - name: my-volume 
        persistentVolumeClaim:
          claimName: nfs-pvc 
         







...
