---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service 
  namespace: nginx-namespace 
spec: 
  type: NodePort
  ports: 
  - targetPort: 80
    port: 80
    nodePort: 30080
  selector: 
    app: nginx

...
